# Generated by Django 4.2.2 on 2024-01-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="entry_mol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_mol", models.CharField(max_length=200)),
                ("text_mol", models.TextField()),
                ("dotsketch_mol", models.ImageField(upload_to="sketches")),
                ("dotmol_mol", models.FileField(upload_to="mol_files")),
            ],
        ),
    ]
